services:
  postgres:
    image: postgres:18
    container_name: postgres
    env_file: .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./sql/initdb:/docker-entrypoint-initdb.d:ro
      - ./sql/course-data:/course-data:ro
    restart: unless-stopped

volumes:
  pgdata:
