[project]
name = "postgres-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "polars>=1.42.1",
    "psycopg2-binary>=2.9.12",
]

[dependency-groups]
dev = [
    "nbstripout>=0.9.1",
    "python-dotenv>=1.2.4",
    "types-psycopg2>=2.9.21.20260712",
]
